import os
import streamlit as st
import pandas as pd
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI

# Konfigurasi Halaman Dashboard
st.set_page_config(
    page_title="FleetOps AI Command Center - Marine Operations",
    page_icon="⚓",
    layout="wide"
)

# Judul Utama Aplikasi
st.title("⚓ FleetOps AI Command Center")
st.markdown("### Sistem Manajemen Terpadu Marine Superintendent, Operations Manager, & DPA")
st.markdown("---")

# Sidebar untuk Pengaturan API Key dan Navigasi
st.sidebar.header("🔑 Konfigurasi Sistem")
api_key_input = st.sidebar.text_input("Masukkan OpenAI API Key:", type="password")

st.sidebar.markdown("---")
st.sidebar.header("🤖 200 AI Workforce Control")
menu = st.sidebar.selectbox(
    "Pilih Panel Divisi AI:",
    [
        "📊 Executive Dashboard",
        "🛡️ Div 1: Safety & DPA Agent Hub",
        "⚙️ Div 2: Marine Operations & Tech",
        "👥 Div 3: Crewing & Welfare",
        "📜 Div 4: Commercial & Claims"
    ]
)

# Simulasi Database Armada Real-Time
fleet_data = pd.DataFrame({
    "Nama Kapal": ["MV Samudera 01", "MT Baruna Jaya", "TB Mitra Samudra", "AHTS Pegasus"],
    "Tipe": ["Bulk Carrier", "Oil Tanker", "Tugboat", "Offshore Support"],
    "Lokasi / Status": ["Singapura (Anchorage)", "Malacca Strait (En route)", "Batam (Ops)", "Jawa Sea (Spot)"],
    "Status Safety (DPA)": ["🟢 Aman", "🟢 Aman", "🟡 Warning (Near-miss)", "🟢 Aman"],
    "Bunker Efficiency": ["Optimal (+2%)", "Boros (-5%)", "Optimal (0%)", "Optimal (+1%)"],
    "Sertifikat Kritis": ["Valid", "Valid", "Renewal 14 Hari", "Valid"]
})

if "Executive" in menu:
    st.subheader("📋 Ringkasan Eksekutif Harian (Generated by AI)")
    
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric(label="Total Armada Dipantau", value="4 Kapal", delta="Aktif 100%")
    with col2:
        st.metric(label="Status Kepatuhan ISM/DPA", value="98.5%", delta="-0.5%")
    with col3:
        st.metric(label="Efisiensi Bahan Bakar", value="94.2%", delta="+1.2%")
    with col4:
        st.metric(label="Open Incidents / Near Miss", value="1 Kasus", delta="Investigasi AI Aktif")

    st.markdown("### 📊 Status Armada Saat Ini")
    st.dataframe(fleet_data, use_container_width=True)

    st.markdown("### 🤖 Live AI Agent Notifications")
    st.info("💡 **AI DPA Assistant:** Ditemukan *near-miss* prosedur *mooring* di TB Mitra Samudra. Laporan RCA otomatis telah disusun.")
    st.warning("⚠️ **AI Compliance Tracker:** Sertifikat *Load Line* untuk MT Baruna Jaya mendekati masa akhir (14 hari lagi).")

elif "Safety" in menu:
    st.subheader("🛡️ Fleet Safety, Quality & DPA Support Team (AI Multi-Agent Execution)")
    st.markdown("Modul interaktif untuk menguji kolaborasi agen AI (DPA, Superintendent, Operations) secara langsung.")
    
    custom_incident = st.text_area(
        "Masukkan Laporan Insiden / Tugas untuk Tim AI:", 
        "Terjadi near-miss saat proses mooring di TB Mitra Samudra akibat tali putus."
    )
    
    if st.button("Jalankan Tim AI Multi-Agent"):
        if not api_key_input:
            st.error("⚠️ Mohon masukkan OpenAI API Key terlebih dahulu di sidebar sebelah kiri.")
        else:
            os.environ["OPENAI_API_KEY"] = api_key_input
            with st.spinner("🤖 200 Agen AI sedang berkoordinasi (DPA, Superintendent, & Operations)..."):
                try:
                    # Inisialisasi LLM & Agen CrewAI
                    llm = ChatOpenAI(model="gpt-4o", temperature=0.2)
                    
                    dpa_agent = Agent(
                        role='Chief Designated Person Ashore (DPA)',
                        goal='Memastikan kepatuhan ISM Code dan menganalisis insiden.',
                        backstory="Ahli keselamatan pelayaran senior dengan pengalaman 20 tahun.",
                        verbose=True, llm=llm
                    )
                    
                    superintendent_agent = Agent(
                        role='Lead Marine Superintendent',
                        goal='Mengevaluasi kelayakan teknis alat kapal.',
                        backstory="Superintendent teknik mesin dan dek yang sangat teliti.",
                        verbose=True, llm=llm
                    )

                    task_1 = Task(
                        description=f"Analisis laporan insiden berikut dan buat RCA serta JSA: '{custom_incident}'",
                        expected_output="Laporan investigasi RCA dan draf JSA.",
                        agent=dpa_agent
                    )
                    
                    task_2 = Task(
                        description="Berdasarkan insiden tersebut, berikan rekomendasi perawatan alat dek/mesin terkait.",
                        expected_output="Daftar rekomendasi perawatan preventif.",
                        agent=superintendent_agent
                    )

                    crew = Crew(
                        agents=[dpa_agent, superintendent_agent],
                        tasks=[task_1, task_2],
                        process=Process.sequential
                    )

                    result = crew.kickoff()
                    st.success("✅ Analisis Tim AI Selesai!")
                    st.markdown("### 📄 Hasil Keputusan Eksekutif AI:")
                    st.write(result)
                    
                except Exception as e:
                    st.error(f"Terjadi kesalahan koneksi atau API Key tidak valid: {e}")

elif "Operations" in menu:
    st.subheader("⚙️ Marine Operations & Technical Support Team (60 AI Agent)")
    st.markdown("Modul pemantauan rute, konsumsi bahan bakar (Noon Report), dan efisiensi pelabuhan.")
    st.info("Status: Semua Noon Report hari ini telah divalidasi oleh AI Performance Analyst.")

elif "Crewing" in menu:
    st.subheader("👥 Crewing, Training & Welfare Team (50 AI Agent)")
    st.markdown("Modul pemantauan STCW, sertifikat medis, dan jam istirahat (*Hours of Rest* - MLC 2006).")
    st.info("Status: Kepatuhan MLC 2006 berada pada tingkat 100%. Tidak ada catatan pelanggaran kelelahan kru.")

elif "Commercial" in menu:
    st.subheader("📜 Commercial, Contract & Documentation Team (40 AI Agent)")
    st.markdown("Modul analisis klaim Charter Party, perhitungan *Off-hire*, dan *Demurrage*.")
    st.info("Status: Perhitungan waktu sandar kapal di pelabuhan muat tervalidasi otomatis tanpa selisih klaim.")

# Footer
st.markdown("---")
st.markdown("📌 *FleetOps AI Engine v1.0 | Connected to Autonomous Marine Agents Framework*")
